### ISSUE TITLE
[Discussion] Mods to remove/keep

### ISSUE THREAD

**Issue by JuiceyBeans** [ThePansmith/Monifactory#102]
There are a few mods that could be removed to save on performance in Moni that I found

**Definitely remove:**
- Artan'sProjectCoreMod: Probably a leftover from some removed mod
- Lemon Lib: Used for MiniUtilities, which was removed
- Stack Refill: Functionality already provided by Inventory Tweaks Refoxed
- CIT Resewn: Wait why is this here anyway? Isn't this a Fabric mod?

**Mods that could be removed:**
- AE2 QoL Recipes: All this mod adds is a bunch of recipes, the mod itself is empty otherwise. Could be implemented via KJS instead
- Leaky:  Its unlikely that players will ever build vanilla farms when HNN exists, so its usefulness is incredibly small
- Energy Meter: To be honest, this one can be kept for all that I care, but its a question of if it really adds anything to the pack. Players can add it themselves if they really want to measure their power rates
- 3D Skin Layers: Again, does it really add anything to the pack? Clientside so players who want it can add it themselves
- Showcase Item: Same as above
- Water condenser: Not sure about this one, might be worth looking into if KJS can make a block that outputs water. If so, that would remove the need for this mod entirely
- Ender Crop: With HNN, why is this really requred? Its going to be obsolete so fast and that's assuming the player even obtains it before achieving sim chambers
- Model Gap Fix: Also a client side mod that really adds nothing to the pack. However, I am in favor of keeping this because why is this not in base MC anyway?
- Visual Workbench: Client side, doesn't really add anything
- WaterFrames: Ok yeah, frames are funny for multiplayer. But the mod is like 54MB so is it really worth it? Keep in mind that not many people are going to use it in singleplayer or even in multiplayer for that matter except to goof off
- Wireless Chargers: Not sure how much use this mod will get, Nomi doesn't have any blocks with its functionality either afaik
- Overloaded Armor Bar: What use is this going to have in Moni, a peaceful modpack lol. Plus I don't think there's any actual armors that players will use that needs an overloaded armor bar
- No Recipe Book Reborn: Is the recipe book really that annoying? It only takes up a few pixels on the screen. Plus there will be players (myself included) who use it, even if just to quickcraft from materials available in the inventory
- No Auto Jump: There's going to be SOME people out there who want auto jump. Just ship the pack with it disabled by default in ``options.txt`` instead of adding another mod; this lets the players who want it enable it as well

**Performance mods:**
- Saturn: Testing it myself shows that Saturn actually **_increases_** memory usage by about 400MB. It is to be noted however, that CPU usage is reduced by about ~2-3% however. Spark profiles from testing below
```
Without Saturn: https://spark.lucko.me/sEjlply7b3
With Saturn: https://spark.lucko.me/9KgkF44frf
```
- FTB Quests Optimizer: Not required on client, could just pack it with server files instead
- Smooth Boot: Testing required
- Smooth chunk save: Testing required
- Redirector: Testing required

``This list may be subject to change as I take a closer look at the mod list``

**Comment by esmenard** [comment]
If I understand things correctly the wireless chargers would be useful to charge jetpacks

**Comment by Midius** [comment]
Ender Crop: You gonna need it for HM though, because you can't sim pearls

**Comment by Xefyr0** [comment]
My take, in case anyone actually winds up seeing it:

**Mods we should keep, actually:**
Leaky is something worth keeping with Snad farms being a staple - Even with Greenhouses nothing matches the cost-effectiveness of Snad + observer + piston + vacuum chest.
Ender Crop - As Midius said, it's useful for Hard Mode, because it's more cost-effective than the Be + K +N chemistry recipe and diamond + pulsating dust alloying recipe.

**Mods we should definitely remove:**
Energy Meter - This thing allows for the transfer of up to 1 GFE/t, as opposed to the Draconic Superconductor Conduit's 134MFE/t. If you want conduit progression to have some weight then this is worth removing.
Water Condenser - Pretty sure this one is unnecessary with Primitive Water Pump, infinite water ME drive, Aquaeous Accumulator, and infinite water Gregtech covers.
Wireless chargers - This one devaules the worth of creative jetpack & capacitor since a stable base power supply + wireless charger grants you effectively infinite flight.

Everything else could also be removed without issue, probably?

**Comment by JuiceyBeans** [comment]
Closing this, all discussion is on #115
