### ISSUE TITLE
[bug] Steam boiler/dynamo ratio not correct

### ISSUE THREAD

**Issue by vsn4ke** [ThePansmith/Monifactory#1034]
The steam boiler only produce 80mb/t of steam, not enough to sustain 2 dynamo.

changing back the config from "/serverconfig/systeams-server.toml" to: 
["Steam Values"]
     stirling = 1

correct the problem

**Comment by Silvre** [comment]
yeah i also noticed this issue setting up my boilers. looks like it got fixed with #1019 though, whenever the next version comes out.

**Comment by Xefyr0** [comment]
Yes, this is fixed with #1019.
When the update drops, however, anyone with this issue will need to copy `systeams-server.toml` from the `defaultconfigs` folder to the `serverconfig` folder of their save(s) due to how the configuration files work.

@vsn4ke I should point out that your change 'resolves' the issue, but has the side effect of making Stirling Boilers 2x as efficient. I assume you have likely moved on past steam power by now, though.
