### ISSUE TITLE
[Bug]: Iridium Metal Residue LRC bug

### ISSUE THREAD

**Issue by 4dam3k** [ThePansmith/Monifactory#152]
### Issue Summary

I've built LCR to produce Iridium Metal Residue
It had all required hatches and 4a EV energy hatch
However it didn't run and scanner gave this message:
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/0969c2f5-9c28-42ec-b73c-1dd81d0fb5d1)
Recipe is using 7680EU/t, hatch was full, so was 4a EV converter

After adding another 4a EV energy hatch it worked, but I didn't power it, just put it there and still it work
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/c51faca0-231d-45aa-bdc5-d4802e3cb1e7)

### Reproduction steps

1. Build LCR with 1x 4a EV energy hatch
2. Supply everything for Iridium Metal Residue
3. Doesn't work
4. Add second 4a EV energy hatch, power it or don't
5. Does work

**Comment by ogmon1243** [comment]
This isn't a bug, its intentional. 7680EU/t falls under the IV energy range so the machine needs to have IV energy supplied to process the recipe. While your one EV energy hatch may be able to supply the energy, the machine itself thinks its receiving EV energy. If you use 2 energy hatches, the energy supplied is bumped up a tier. 

For example, if you are trying to do an EV recipe and only have HV hatches, you can power 2 HV hatches in the multiblock to bump the energy tier to EV so that recipe can process. 2x HV -> EV, 2x EV -> IV, etc.

**Comment by 4dam3k** [comment]
> This isn't a bug, its intentional. 7680EU/t falls under the IV energy range so the machine needs to have IV energy supplied to process the recipe. While your one EV energy hatch may be able to supply the energy, the machine itself thinks its receiving EV energy. If you use 2 energy hatches, the energy supplied is bumped up a tier.
>
> For example, if you are trying to do an EV recipe and only have HV hatches, you can power 2 HV hatches in the multiblock to bump the energy tier to EV so that recipe can process. 2x HV -> EV, 2x EV -> IV, etc.

Wasn't that a thing earlier? (speaking Nomi/Omni)
You had to use energy hatches to bump the tier so you can process higher tier recipe

**Comment by ogmon1243** [comment]
Yes exactly. That's why your machine required another hatch
