### ISSUE TITLE
[Bug]: The "Electronic Subcomponents" quest's dependencies require expert mode quests in normal/non-expert mode.

### ISSUE THREAD

**Issue by PinkGreenTaffy** [ThePansmith/Monifactory#172]
### Issue Summary

The "Electronic Subcomponents" quest's dependencies require expert mode quests in normal/non-expert mode. You can complete both "Steel" and "From Dust to Wires" and have the required materials in your inventory, but the quest will be unable to be turned in, as it requires expert mode quests. I was able to figure this out by checking the dependencies for the quest.

### Reproduction steps

1. Complete both the "Steel" and "From Dust to Wires" quests in non-expert mode.
2. The "Electronic Subcomponents" quests will not be highlighted in the quest book, and show it needs expert mode quests "Primitive Blast Furnace" and "From Dust To Wires" to be completed.

**Comment by CestQuoiUnPseudo** [comment]
Exactly. It also makes it possible, by looking through dependencies, to access the "A Harder Genesis" questbook chapters as well as the "dependencies" chapter of which the "undo intro" really tempts me

**Comment by ThePansmith** [comment]
Ah, it's due to it being a linked quest between both version, thus depending on both lines. Fixed.

BTW, you can easily view the hidden chapters by enabling edit mode (running the command or pressing the pencil icon in the bottom right). The Hardmode quests don't have text atm, but help would be appreciated on that.
