### ISSUE TITLE
[Bug]: ME Crafting terminal synthetic favourite (BOM) support 

### ISSUE THREAD

**Issue by jeytee84** [ThePansmith/Monifactory#679]
### Issue Summary

I was wondering if there is a way to get the same EMI functionality in the crafting terminal as in the crafting station.

![2024-09-09_01-34-36_java_Monifactory_(BETA)](https://github.com/user-attachments/assets/a226bb67-465d-4bd9-bedd-bbace0f97d4e)
(EMI finds the already crafted items in the crafting stations connected inventories)

![2024-09-09_01-31-29_java_Monifactory_(BETA)](https://github.com/user-attachments/assets/6873f43f-2810-4223-a8fb-403facc1b692)
(EMI does not see the ME system's content)

The ME system is hooked up to the exact same two aluminium barrels via storage buses

**Comment by jeytee84** [comment]
update, just found the mod fixing this issue in the latest update.
https://modrinth.com/mod/ae2-emi-crafting/changelog
only problem that it's for fabric only but seems like a forge port is in the works
https://github.com/blocovermelho/ae2-emi-crafting/issues/5#issuecomment-2094964813

**Comment by alikindsys** [comment]
About the port to forge, BOM Sync hasn't really been tested on large packs, and it might get *really* laggy and that's why I decided to put that behind an experimental option.

Making that efficient could need doing some wacky mixin into ae2 source code which I'm not looking forward to do.

Seen that I'll likely play this exact pack with my friends in the near future, that save on the server will be the test bed for making BOM Sync work on forge.

**Comment by alikindsys** [comment]
I got a bunch of issues of people running the mod with Connector, so I wouldn't recommend that at all, even though I'm using only API calls from either mod and it should technically work just fine.

**Comment by jeytee84** [comment]
Just tested it on 0.9.5 but it's still not working. Am I missing something?
Is it marked completed because it's coming in the next update or is it not planned at all?

**Comment by jeytee84** [comment]
For reference, a setup with Connector works prefectly for now as detailed [here](https://github.com/ThePansmith/Monifactory/issues/949#issuecomment-2425270999)
