### ISSUE TITLE
[Bug]: Functional storage drawer recipe isn't working correctly

### ISSUE THREAD

**Issue by ajbrink88** [ThePansmith/Monifactory#782]
### Issue Summary

When crafting drawers from functional storage the amount of wood you are using doesn't matter only the amount of chests in the middle, example:

64 chests surrounded by 8 wooden planks, the output should be 1 drawer.
![image](https://github.com/user-attachments/assets/730336ab-4f00-4dbf-a4a3-c1d4a8fdd1e0)

64 drawers are crafted when shift clicking to craft
![image](https://github.com/user-attachments/assets/f2f8b385-a915-416b-9b4b-9c9b85b57caf)

### Reproduction steps

1. Open handheld crafting table or crafting table
2. Put larger amount of chests in the middle slot of the recipe and 1 wood in all other slots
3. Shift click on the output of the craft and you will get the amount of drawers that you put in chests

**Comment by klaborda** [comment]
This one is interesting since I don't see any specific recipe overrides for the drawer recipe https://github.com/ThePansmith/Monifactory/blob/69385f7c298ded81bca1c0f7546a78a77f3b0763/kubejs/server_scripts/mods/functionalstorage.js#L12

Interesting!

**Comment by erencank** [comment]
If you put a chest in the middle crafting slot, it also gives you a drawer. So there might be 2 recipes for it. One with wood around it and one without. The one with wood can be used to get drawers with different wood types. So, is this behaviour then correct? Since it made 1 drawer by using the recipe with 1 chest and 8x wood planks and 63x the recipe of just a chest in the middle slot.

**Comment by Xefyr0** [comment]
Fixed in #826
