### ISSUE TITLE
[Bug]: Compacting drawer seems useless?

### ISSUE THREAD

**Issue by Niki4tap** [ThePansmith/Monifactory#894]
### Issue Summary

(Harder mode, moni version 0.8.1)

Compacting drawer seems to be nothing more than a regular drawer, due to its inability to compact anything.

Tried coins, which are seemingly not compacting due to https://github.com/ThePansmith/Monifactory/commit/8dc1d49c4a1b3d3ce11a1292fe9a430f9f93ee4e, that removed this feature in hard(er) modes (why???)
Tried greg dusts (tiny, small), ingots (blocks) and well every other item in the game, nothing seems to be compacting in this drawer at all

If it's an upstream issue, might want a warning in the quest book or an explicit mention in KNOWN-ISSUES.md, and if it's intended to be useless, remove it?

!["compacting" drawers](https://github.com/user-attachments/assets/9125a290-4eb2-4c0c-a222-acba36cc4b08)

### Reproduction steps

1) Try to compact anything in the compacting drawer
2) Fail

**Comment by MightyPiggie** [comment]
Mmmh weird I am on normal mode on version 0.8.5 and for me it is working just fine. (Well I've only tested sand so far). Does anything change if you put the item in another slot?

**Comment by OrioPrisco** [comment]
Sand does work on harder mode too

**Comment by Niki4tap** [comment]
Well I haven't tested sand when I made the screenshot, but compressing only sand doesn't sound much more useful that being able to compress nothing. As I've mentioned previously in nomi I mainly used these for dusts and ingots/blocks, not sand, so still an issue for me

**Comment by Xefyr0** [comment]
It seems more like an issue on your end rather than the pack. Try restarting/reinstalling, the whole gamut of standard troubleshooting techniques. If that doesn't work, Seek help in the #moni-support channel of the Discord.
![worksonmymachine](https://github.com/user-attachments/assets/4496d112-f5ab-41c1-9a41-d2154d18cab6)

**Comment by Niki4tap** [comment]
> It seems more like an issue on your end rather than the pack. Try restarting/reinstalling, the whole gamut of standard troubleshooting techniques. If that doesn't work, Seek help in the #moni-support channel of the Discord. ![worksonmymachine](https://private-user-images.githubusercontent.com/78383477/375928252-4496d112-f5ab-41c1-9a41-d2154d18cab6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDEzNTgsIm5iZiI6MTcyODc0MTA1OCwicGF0aCI6Ii83ODM4MzQ3Ny8zNzU5MjgyNTItNDQ5NmQxMTItZjVhYi00MWMxLTlhNDEtZDIxNTRkMThjYWI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEzNTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODA4NjkzODBiYjBiN2U4ZjE0NDBhMjQ0ZjE4N2ZlM2I0MzBkZWUyZTZjZGNlODM3OGE2MTE5MDdmNjNiNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WVM6epVAfQ2YwRwsdaRY7ZINa6okgAl4hf8WutKC2eA)

Just had more time to test, apparently these *do* work as expected on normal mode, on harder mode still looks broken

**Comment by Niki4tap** [comment]
@Xefyr0 Sorry for mention if you have seen the previous comment already, just making sure you're aware the issue is still present, would be great if you have the opportunity to test this on harder mode and possibly reopen the issue, thanks!

**Comment by Xefyr0** [comment]
if it works on Normal Mode but not on Harder mode, you're probably expecting compacting drawers to perform compacting recipes on ingots, nuggets, and blocks of metals, yes?

In harder mode many recipes for compacting and decompacting metals through the crafting table have been removed. The drawer relies on these recipes to decide what items it can compact/decompact, and accordingly _they don't work in harder._

This is intentional behavior! Compacting and decompacting in Harder are supposed to be performed in the Alloy Smelter, and so it's a good thing that you can't circumvent that with Compacting Drawers.

**Comment by Niki4tap** [comment]
Ah yep, that would make sense, to be fair I haven't used compacting drawers outside of that, so if it was up to me I would just remove it since other compacting recipes wouldn't be used very much (while playing nomi I haven't used them for any other purpose than dusts and ingots).

Now I understand why it is like that, I think it would be nice to clear up some confusion and mention it in the README (maybe?), of course I would very much prefer if there was a comprehensive list of hard(er) mode changes, but at least mentioning it in the hard(er) mode highlights would do it for me
