### ISSUE TITLE
[Feature]: Patchouli Guide Books

### ISSUE THREAD

**Issue by CommanderT3706** [ThePansmith/Monifactory#916]
### Suggestion

LaserIO seems to be one of the main logistics mods in the pack. However, I personally struggled to figure out how everything worked as it was my first time using the mod. LaserIO includes in-game documentation which can be accessed via a Patchouli book. Having access to the guide should make it easier for new players to be introduced to the mod

**Comment by Xefyr0** [comment]
Most patchouli guide books include information about removed items or altered behavior.
- Most of the machines in Nuclearcraft's guide book have been removed
- LaserIO's Logic Chips are no longer used as a crafting ingredient
- ExtendedCrafting's Ender Crafting, Compressor Crafting are irrelevant due to those items having been removed
- EnderIO's guide book is what appears to be the default, test guidebook
- Much of the information in the Thermalpedia is no longer accurate with Monifactory's alterations to TE recipes

@ThePansmith your call on whether to
1. Drop the idea entirely
2. Add the mod, then remove the incorrect pages through datapacks and make the unsalvageable books unobtainable
