### ISSUE TITLE
[Bug]: Blocks turning into everything but what they should be

### ISSUE THREAD

**Issue by Slothfulsins** [ThePansmith/Monifactory#953]
### Issue Summary

Spruce ladders turn into nether furnaces and can't be climbed
Enderchests turn into a shale brick verticle slab with water if placed on the ground. When placed on a wall it will be the correct item but shows no hud
Enderchests with previous channels comes back as "No available hud data from server"
Spruce drawer (1x1) turns into Rubberwood drawer (1x1)
Oak drawers (1x1) turn into treated wood drawer (1x1)
Pressurized conduits turn into soul furnaces
and so on.

Reverting from 0.9.7 to 0.9.5 resolved the issue, but 9.7 is unplayable

### Reproduction steps

Place any one of those items to test, on a multiplayer server. **edited to add multiplayer

### Relevant log output

```shell
None. All visual/in game
```

**Comment by Slothfulsins** [comment]
![enderchest2](https://github.com/user-attachments/assets/680cbf92-ed2e-41ab-aae9-fce0c9710794)
![enderchest](https://github.com/user-attachments/assets/e54689ec-97df-43bb-9a91-2ee783b90b0f)

**Comment by WithersChat** [comment]
Can't reproduce the bug with the given instructions. Spruce ladder and ender chests behave perfectly normally.

**Comment by Slothfulsins** [comment]
This happens on servers. It's definitely repeatable as every player on the server had the issue.

**Comment by Xefyr0** [comment]
Other servers have not reported this issue, and a few hotfixes have occurred since this report was made.
If you update and this is still an issue, then make a new post with more information - you have not provided enough for us to properly troubleshoot.

I highly recommend following the update instructions in the [FAQ](https://github.com/ThePansmith/Monifactory/blob/main/FAQ.md#how-do-i) and doing the equivalent for the server - some launchers do not clear out previous modpack versions' files when they update which may be involved somehow.

**Comment by Slothfulsins** [comment]
Hilarious. We've removed the pack from our network, as it is not stable enough to run with even 2+ players consistently. Optimization is clearly not a strong suit for the developers here.
