### ISSUE TITLE
[Bug]: My Steam turbine producing only 40 RF/t

### ISSUE THREAD

**Issue by WarZzo** [ThePansmith/Monifactory#968]
### Issue Summary

I was looking at this video : (https://youtu.be/LVSTXlasny4?si=qBObd-cKa4f1GRu1&t=1131) and when i reproduced the setup i realized that mine only produced 40 RF/T non modified and seems a bit low.

### Reproduction steps

1. Place stream boiler
2. pipe it to the steam turbine
3. open energy menu
4.only 40RF/T
![image](https://github.com/user-attachments/assets/00b3c4ae-e534-4ce5-9bf5-fd8ccf039c45)

**Comment by Kasra-G** [comment]
Noticed this as well, I thought the change here #735 was only supposed to change the fuel efficiency of the boiler?

Seems that it was a side effect of the change. 
These lines are probably the cause:
https://github.com/ThePansmith/Monifactory/pull/735/files#diff-8dd987cccec93b1f50c15f125a8bbff3d674d9738414fea90b973e7a1b015767L8-R8

**Comment by MightyPiggie** [comment]
> Edit: Can confirm that changing the multiplier back to 4.0 in the config brings back the 160 rf/t turbines

If that is indeed the issue try updating the pack to the latest version. The change should be reverted back to 4.0:
https://github.com/ThePansmith/Monifactory/commit/87efb2ddb0ae59e2a1b460662a8acb8037d4b368#diff-8dd987cccec93b1f50c15f125a8bbff3d674d9738414fea90b973e7a1b015767R8

**Comment by sp4rkyd4rk** [comment]
Heya! Changing it server-wide didn't help me. Even though I'm now updated to 0.9.10 version of the pack (the one from 17 hours ago from time of posting). Both upgraded and regular turbines are still on 40 and 60 rf/t. And my `defaultconfigs/systeams-server.toml` is reversed to 4.0 multi. 

I'm kinda confused rn about what to do with that. I tried crafting new turbines, reseating previous ones, reseating upgrade, changing multiplier couple times more. Nothing happened and idk why.

![image](https://github.com/user-attachments/assets/0a2ebc71-98e3-4c1a-b80a-8bbbd72c9e5a)
![image](https://github.com/user-attachments/assets/d6f876a6-8d02-4464-a349-a24e5c803b77)
![image](https://github.com/user-attachments/assets/234f242c-32a6-486a-b2cb-61c573cfe0b3)

**Comment by WarZzo** [comment]
You have a systeams-servers file in the save file you need to chnage it there for it to work or at least that worked for me and becarful you need to have your game close for the file to save.( May work if in main menu dont know never tested)

**Comment by Kasra-G** [comment]
This goes back to the way configs are handled by Forge. No changes in defaultconfigs will change existing worlds. The original user had this issue because they created a new world after the issue was introduced but before it was fixed again.

If you actually want the defaultconfig changes to propagate you will need to delete/overwrite the file that had changes (in this case, `serverconfig/systeams-server.toml`) in your save folder and reload the world.

I forget if there's a more integrated way to do this, but regardless it would be nice if we could get a message in the release notes if the `defaultconfig` folder was modified so that we can know to manually overwrite the `serverconfig` files in our levels with the new configs.

**Comment by sp4rkyd4rk** [comment]
Hey! Thanks for the heads-up! Never noticed that serverconfig folder, gotta
try it out.
Also that's also the way I got my world into the issue, the world was
started in 0.9.7 which already had it.

Never used forge on "new" versions so I didn't know defaultconfig
propagates into every new world generated. Cheers!
